name: ci

on:
  push:
    branches: [main]

jobs:
  build_and_push:
    runs-on: wallet
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build images
        run: ./scripts/build.sh
      - name: Push images
        run: ./scripts/push.sh

  deploy:
    needs: build_and_push
    runs-on: wallet
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Pull docker images
        run: ./scripts/pull.sh
      - name: Deploy
        run: ./scripts/deploy.sh
